### ISSUE TITLE
Emulationstation Ports do not work. 

### ISSUE THREAD

**Issue by Serg86** [bite-your-idols/Gamestarter-Pi#12]
Raspberry Pi 2
Libreelec 7.0.2
Gamestarter 2.1.1

Trying to run ports from ES menu goes to black screen for a second, then returns to ES.

None of them work from ES, but all are installed correctly. I managed to run Doom and Cave Story from Retroarch for example.

**Comment by bite-your-idols** [comment]
-can you try to launch them using advancedlauncher?
-did you downloaded the ports using retroarch or they are the ones I included, located in /storage/emulators/roms/ports/ ?
- can you take a look to /storage/.config/gamestarter.log file?

**Comment by Serg86** [comment]
It's a default gamestarter install. Log says the path to the retroarch binary does not exist in the .sh files. I guess Advanced Launcher will not work either if it's the scripts themselves.

**Comment by bite-your-idols** [comment]
ok. Fixed. Retroarch path was wrong :(
You can reinstall latest pre-release or just download this package and extract sh files from ports folder:
https://github.com/bite-your-idols/Gamestarter-Pi/blob/2.1.1/resources/data/emulators.tar.gz

**Comment by Serg86** [comment]
Thank you, but that only fixed Cave Story and Doom, without sound though.

I tried every game top to bottom in ES, here's the gamestarter.log: http://pastebin.com/QYEETQdj

I did reboot after installing the gamemaker ports from the addon settings menu.

**Comment by bite-your-idols** [comment]
Dinothawr wont work because I didn't include it, just the launcher file, you need to dowload maually and place in ports folder.
For Gamemaker ports you need toactivate Hacklib addon first.
Quake must work as cavestory and doom do.

**Comment by Serg86** [comment]
I uninstalled Adv Launcher, Gamestarter and Hacklib, deleted all config folders, rebooted and reinstalled gamestarter. Doom and Cave Story work with sound now, Quake doesn't work from ES.

I can launch it by starting Doom from ES, quitting Doom, loading Quake1 core and loading pak0.pak.

**Comment by bite-your-idols** [comment]
fixed! thanks for your report.
