### ISSUE TITLE
USB gamepads not working

### ISSUE THREAD

**Issue by kwazaro** [bite-your-idols/Gamestarter-Pi#13]
I have two different generic USB gamepads (Gembird and Acme) and they seems not recognized by system (Libreelec 7.0.2 on Rpi2). On Retropie version 3.7 they works fine, but on Retropie 3.8 one of them doesn't work (Gembird is out, only Acme works - maybe it's linux kernel issue). Also on Lakka Gembird is working fine, but Acme doesn't work (Lakka-RPi2.arm-devel-20160811145614-r21565-gc79651a.tar). On Libreelec with connected Gembird ```ls /dev/input``` shows only ```by-id    by-path  event0   event1   mice     mouse0```, the LED on gamepad is green and not changing while pressing the mode button (normally the led switches to red/green).
How can I use these gamepads with Gamestarter addon? Maybe there is specific configs or plugins for Kodi to activate gamepads different from Xbox and PS?

**Comment by bite-your-idols** [comment]
When in retropie 3.7, check what name is giving retroarch for each one of them, then copy the same name config file from joystick configs folder (I don't know where retroarch stores them), then paste it in /storage/.config/retroarch/autoconfig/

I can't tell if this will work but it is what I would do first.

**Comment by kwazaro** [comment]
I made the above, there is no effect.

**Comment by bite-your-idols** [comment]
Ok, so I am sorry to tell you that your gamepads seem that will not work... Maybe you can try librelec 8 alpha that includes native support for gamepads.. Or ask for help in librelec forums...

**Comment by kwazaro** [comment]
I tried alpha version of Libreelec with different joypad profiles installed - nothing at all.

**Comment by kwazaro** [comment]
Both joypads works fine on Retropie 4.0.2 after raspberry pi kernel update with "rpi-update" over SSH. But what about kodi?

**Comment by bite-your-idols** [comment]
I think you need to ask in LibreELEC forums because it is not related with my addon, sorry.
