### ISSUE TITLE
Emulationstation doesn't start properly

### ISSUE THREAD

**Issue by TalmarGrosskotz** [bite-your-idols/Gamestarter-Pi#14]
When I try to start Gamestarter with Emulationstation as a frontend it only goes to libreelec's start splsahup. any ideas what i am doing wrong?

**Comment by bite-your-idols** [comment]
First, you need to install EmultionStation from addon settings, then reboot and launch it.

**Comment by MariusWHV** [comment]
I have the same problem here. When I start emulationstation manually I get:
/var/media/kodi/kodidata/addons/script.gamestarter/resources/bin/emulationstation: symbol lookup error: /var/media/kodi/kodidata/addons/script.gamestarter/lib/libfreeimage.so.3: undefined symbol: png_init_filter_functions_neon

**Comment by bite-your-idols** [comment]
what OS are you using? make sure you are using addon's latest release.

**Comment by MariusWHV** [comment]
I use the latest Gamestarter Alpha build and Libreelec (Milhouse) Kodi 17.0 Beta2

**Comment by bite-your-idols** [comment]
ok, I need to check it, with LibreELEC 8 official alpha 5 it works ok...

**Comment by bite-your-idols** [comment]
Ok, There is a problem with Emulationstation in latest mildhouse developers build of LibreELEC, so if you want to use LibreELEC 8/kodi krypton you can use alpha 5 from libreELECs website, it will work.

Mildhouse builds are building daily so are only recommended for developers, when next alpha or beta of LE8 will be released we will check if ES need any fix.
