### ISSUE TITLE
Adding other emulators?

### ISSUE THREAD

**Issue by TalmarGrosskotz** [bite-your-idols/Gamestarter-Pi#15]
Hi I found some libreto files under [https://github.com/escalade/LibreELEC.tv/tree/emu/packages/escalade/emulation](https://github.com/escalade/LibreELEC.tv/tree/emu/packages/escalade/emulation)
and wondered if I could somehow use them under gamestarter as well. 

Especially the vice, dosbox, and scumm would be interesting.

**Comment by bite-your-idols** [comment]
vice and dosbox are not libretro cores but standalone emulators. 
On the other hand you can use Scummvm libretro with gamestarter, indeed you can download it in this package I have prepared with some experimental cores:
https://github.com/bite-your-idols/Gamestarter-Pi/raw/master/resources/data/libretro-part3.tar.gz

just unpack and copy the core into /storage/.config/retroarch/cores/ then you can start emulator from retroarch or create a new category in AdvancedLauncher or emulationstation.
