### ISSUE TITLE
Retroarch audio problem / RPI3 / HDMI

### ISSUE THREAD

**Issue by obermotz** [bite-your-idols/Gamestarter-Pi#16]
Hi, I have no audio on my RPI3 in Retroarch. I installed v2.2, have audio in Libreelec but only silence in Retroarch. Can you please advise on this?

**Comment by bite-your-idols** [comment]
Let's see...
OS? 
hdmi audio output?

check this out: https://forum.libreelec.tv/thread-287-post-6786.html#pid6786
