### ISSUE TITLE
Recursive AdvancedLauncher error on first run.

### ISSUE THREAD

**Issue by DarthLordi** [bite-your-idols/Gamestarter-Pi#18]
I've just installed Gamestarter v2.4 on a fresh install of LibreElec 7.0.2.
When running the first-start-setup it just runs and runs. I left it for an hour and it was still configuring.
Looking at \storage\.config\AdvancedLauncher in file manager I noticed AdvancedLauncher had been recursively installing itself in \storage\.config\AdvancedLauncher\AdvancedLauncher\.... Until the disc was full. I needed to rename the folders before deleting them as the path was too long.

**Comment by bite-your-idols** [comment]
It should work. Please, make sure you are using the correct addon vesion (OLE), try to install again and paste here the output in /storage/.config/gamestarter.log

**Comment by DarthLordi** [comment]
I'm trying to install script.gamestarter-v2.4-OLE.zip.

gamestarter.log
::Gamestarter:: -> installation on  Fri Sep 16 22:38:07 BST 2016
::Gamestarter:: -> installing in Open/LibreELEC...
::Gamestarter:: -> edit config.txt...
::Gamestarter:: -> script permissions...
::Gamestarter:: -> copying packages...
::Gamestarter:: -> installing advanced launcher...
Connecting to github.com (192.30.253.113:443)

**Comment by bite-your-idols** [comment]
I just test it again in a fresh new LE 7.0.2 installation and works ok...

At that installation point you must have a folder called advancedlauncher in /storage/.config/ and a symlink in storage/.kodi/userdata/addon_data/, correct?

Also at that point it is installing AL addon from github, so can you check if there is the advancedlauncher addon folder in /storage/.kodi/addons/ and if this addon works? maybe a internet connection issue?

you can test using ssh with this lines, one by one:
`ADDON_DIRECTORY="/storage/.kodi/addons/script.gamestarter"
CONFIG_DIRECTORY="/storage/.config"
ROOT_DIRECTORY="/storage"
wget --no-check-certificate -O $ROOT_DIRECTORY/advancedemulatorlauncher.zip https://github.com/bite-your-idols/Gamestarter-Pi/raw/master/packages/plugin.program.advanced.emulator.launcher.tar.gz
	unzip $ROOT_DIRECTORY/advancedemulatorlauncher.zip -d $ROOT_DIRECTORY/.kodi/addons/
	rm $ROOT_DIRECTORY/advancedemulatorlauncher.zip
	mkdir -p $ROOT_DIRECTORY/.kodi/userdata/addon_data/plugin.program.advanced.emulator.launcher
	tar -xf $ADDON_DIRECTORY/resources/data/advancedemulatorlauncher.tar.gz -C $ROOT_DIRECTORY/.kodi/userdata/addon_data/plugin.program.advanced.emulator.launcher -xz
	mv -v $ROOT_DIRECTORY/.kodi/userdata/addon_data/plugin.program.advanced.emulator.launcher/advancedemulatorlauncher/* $ROOT_DIRECTORY/.kodi/userdata/addon_data/plugin.program.advanced.emulator.launcher/
	rm $ROOT_DIRECTORY/.kodi/userdata/addon_data/plugin.program.advanced.emulator.launcher/advancedemulatorlauncher`

**Comment by DarthLordi** [comment]
It appears to hang on:
ROOT_DIRECTORY="/storage" wget --no-check-certificate -O $ROOT_DIRECTORY/advancedemulatorlauncher.zip https://github.com/bite-your-idols/Gamestarter-Pi/raw/master/packages/plugin.program.advanced.emulator.launcher.tar.gz unzip 
Connecting to github.com (192.30.253.113:443)

Other internet applications on Kodi appear to work fine. I can access the link from my laptop on the same network.

**Comment by bite-your-idols** [comment]
and when you access via ssh and exec the command does it tell you any output?

`wget --no-check-certificate -O  storage/advancedemulatorlauncher.zip https://github.com/bite-your-idols/Gamestarter-Pi/raw/master/packages/plugin.program.advanced.emulator.launcher.tar.gz`

and then:

`unzip /storage/advancedemulatorlauncher.zip -d /storage/.kodi/addons/`

**Comment by DarthLordi** [comment]
No further output after that line. Just hangs.

I'm going to try a fresh install of LibreELEC as I was using an OpenELEC installaion freshly updated to LibreELEC to see if there is any difference.

**Comment by bite-your-idols** [comment]
sorry, if you are running LE 7.0.2 you must try these commands, no the previous ones:

tar -xf /storage/.kodi/addons/script.gamestarter/resources/data/advancedlauncher.tar.gz -C /storage/.config/ -xz

`wget --no-check-certificate -O /storage/advancedlauncher.zip https://github.com/bite-your-idols/Gamestarter-Pi/raw/master/packages/advanced-launcher-2.5.8.zip`

`unzip /storage/advancedlauncher.zip -d /storage/.kodi/addons/`
