### ISSUE TITLE
X86 port

### ISSUE THREAD

**Issue by Lampwick** [bite-your-idols/Gamestarter-Pi#21]
Do you have any plans to port this to X86? I'd love to use this on my libreelec media centre but it's running on an old ACER HTPC not a Pi.

**Comment by chewvodka** [comment]
I would imagine not.. the name is "Gamestarter-Pi" for a reason..  I personally am confused though as to why you're running LibreELEC on an x86 capable PC..  Can't you just install Kodi for Windows, and in turn also install Retroarch/etc?  Unless there are some benefits to installing LibreELEC (like being extremely small, no install/setup really required).  Besides that, you can install RetroArch outright, it's self-contained in it's own folder.  The only thing you'd be missing is Gamestarter's scripts to close down Kodi, which you can always do manually.

**Comment by bite-your-idols** [comment]
Chewvodka is right, it is a Pi-Only project...
But you can take a look to this LE custom build, it is awesome:
https://forum.libreelec.tv/thread-302.html
