### ISSUE TITLE
retroarch and emulationstation not running on pi 1 model B

### ISSUE THREAD

**Issue by FREEZX** [bite-your-idols/Gamestarter-Pi#24]
Trying to run gamestarter with retroarch, screen goes black and kodi just restarts. The same thing happens with both 2.4 and 2.5
Looked around and found the log:

```
Illegal instruction (core dumped)

::Gamestarter:: -> disable alsa...
::Gamestarter:: -> restart kodi...
```

**Comment by bite-your-idols** [comment]
They both are compiled for RPi 2/3. 
Sorry.

**Comment by FREEZX** [comment]
Is there an issue preventing us from compiling them for the pi 1/zero?

**Comment by bite-your-idols** [comment]
I have no Pi1 so I can not test, but you can burn Pi1 retropie version into your sd card and pick up retroarch and emulationstation binaries. The burn back your LibreELEC/OpenELEC image and overwrite both binaries in gamestarter addon folder.

**Comment by FREEZX** [comment]
@bite-your-idols Thanks, i'll try that out, i'll post back my results.

**Comment by FREEZX** [comment]
@bite-your-idols Got retroarch to run.
Had to also copy some .so files from retropie as well:
https://gyazo.com/42dd159dd12b8e511e11402a91843f87
And the cores had to be copied from retropie as well.

I got pokemon yellow to work with the gambatte core.
Retroarch crashed several times when i pressed a button (i think RT or RB on my xbox 360 controller), giving out a Segmentation fault (core dumped)
I'll post back when i fix the issues and make sure the other cores are working properly.
Oh, i also have no sound:
```
 /home/chewitt/LibreELEC.70-official/build.LibreELEC-RPi.arm-7.0.2/alsa-lib-1.1.1/src/pcm/pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM
```

**Comment by FREEZX** [comment]
Ok, i made some more progress:
I copied all the cores from RetroPie, they seem to be working fine (Got Crash Team Racing running on PSX ReArmed, lower fps but playable on the pi 1). Got sound to work and no weird crashes. I also had to overwrite the Gamestarter-provided lib files.

EmulationStation is a different story. I had to copy a big number of .so files from retropie and dropped them in the lib folder of the addon for the binary to not complain and not crash with Illegal Instruction (core dumped). When it finally stopped complaining and tried to do anything, i got something like this:

```
lvl0: Error creating SDL window!
Could not initialize OpenGL / GLES library
lvl0: Renderer failed to initialize!
lvl0: Window failed to initialize!
```

I assume this has to do with messed up or incorrect library files.
I'm trying to setup a LibreELEC 7.0.2 toolchain so i can build all the stuff from scratch. So far i compiled LibreELEC but i have no idea how to compile something using it's toolchain.

**Comment by bite-your-idols** [comment]
you have to copy the package files you want to compile like I did in this folder:
https://github.com/bite-your-idols/LibreELEC.tv/tree/master/packages/gamestarter

Edit package.mk files to your needs. 
Then exec: PROJECT=RPi ARCH=arm scripts/build packagename

**Comment by FREEZX** [comment]
Nice, thank you, i'll try it out!

**Comment by bite-your-idols** [comment]
Better than picking up cores from Retropie it will be picking them from Lakka, it is based on OpenELEC and all of them will work without additional libraries. Only thing you will need from retropie is emulationstation that is not present in lakka.
