### ISSUE TITLE
games/bios load from USB

### ISSUE THREAD

**Issue by drrak** [bite-your-idols/Gamestarter-Pi#25]
_Google translator:_
How to set RetroArch, to load a game from USB?

Gamestarter v2.5
LibreELEC 7.0.2, RPi2

**Comment by bite-your-idols** [comment]
in retroarch got to "settings" column, look for "folder" option and enter, then look for navigation folder and change the path from /storage/emulators/roms to the new path you want. Also you can do it with bios and save folders. Then go back to retroarch first column and select save current config file.

**Comment by drrak** [comment]
Thanks.
