### ISSUE TITLE
GBA emulators, *.sav file

### ISSUE THREAD

**Issue by drrak** [bite-your-idols/Gamestarter-Pi#28]
_Google Translator:_
The default GBA emulator ("GPSP") does not work. I changed it for a second, "MGBA", and the emulator works, unfortunately, the old *.sav files are invisible to the "MGBA".

Yes, I know, it has more to do with RetroArch as Gamestarter, but maybe you can help me.

Gamestarter v2.5
LibreELEC 7.0.2, RPi2

**Comment by bite-your-idols** [comment]
savestates are not compatible between cores but memory card/savefiles are.
