### ISSUE TITLE
Retroarch doesn't start

### ISSUE THREAD

**Issue by jbtrystram** [bite-your-idols/Gamestarter-Pi#29]
I just tried this on a fresh install of LibreElec, retroarch does not start : the screen goes black after confirmation on kodi exit, then kodi start again. 

Emulation station is running fine though (but i don't understand how to get IARL working with it.)
I'm running on a raspberry pi 2.

Thanks !

**Comment by bite-your-idols** [comment]
Please provide output log file (/storage/.kodi/userdata/addon_data/script.gamestarter/gamestarter.log)

Are you using the right addon version for your LE version?

**Comment by jbtrystram** [comment]
oh, my bad. I wasn't running the correct version ! I have openElec 7.0.2
I uninstalled Gamestarter then re-installed the proper version.

Still doesn't start... :(
'''
LibreELEC:~ # cat /storage/.kodi/userdata/addon_data/script.gamestarter/gamestarter.log
Running as unit run-r09a24076a8f745ee993eac052dcba481.service.
::Gamestarter:: -> launching on Wed Nov 9 22:27:31 CET 2016
::Gamestarter:: -> stop kodi...
::Gamestarter:: -> enable alsa...
::Gamestarter:: -> launch emulationstation
::Gamestarter:: -> disable alsa...
::Gamestarter:: -> restart kodi...
LibreELEC:~ # 
'''
