### ISSUE TITLE
Manual instalation on Archlinux

### ISSUE THREAD

**Issue by danifr** [bite-your-idols/Gamestarter-Pi#32]
Hola,

he visto que el resto de issues están en inglés así que continuo en el idioma de Shakespeare :)

I was taking a look to this project and I think this is exactly what I was looking for.
Currently I'm running Archlinux on my Raspberry Pi2 where I also have installed kodi.
Apart from this set up, I have some different things configured and running so installing something new (aka LibreELEC) from scratch wouldn't be an option for me.

I was taking a look at the scripts and I does not seem there are many Open/LibreELEC specifics there (apart from file paths and so on).

Do you think it would be possible to install it and make it work on my system?
My idea is taking one of the latest version you published, unzip it, change paths, zip it again and try install it.
Is this a stupid idea? Am I missing something?

Thanks a lot!!!
Dani.

**Comment by bite-your-idols** [comment]
Short answer: 
sorry it is developed for Pi's Libre/ELEC only, I can not test in your OS but I assume retroarch & emulationstation will not run.

Long answer:
Pues eso, que los binarios de retroarch y emulationstation estan compilados usando como toolchain LibreELEC por lo que puedes probar a cambiar las rutas una vez instalado y lanzar el addon a ver que te dice en el log, pero no funcionará. No se si podrás conseguir/compilar retroarch para archlinux y reemplazarlo, con eso y las rutas cambiadas debería funcionar.

**Comment by danifr** [comment]
So... this is going to be a little bit more challenging than I expected...

I was able to install the plugin and replace the binaries (just emulationstation for now) but I'm getting errors every time I open the plugin. I think they are due to permission issues (LibreElec uses root for pretty much everything but in my case I'm using a very right limited user)

If I finally manage to get something working I'll link the steps here.

Muchísimas gracias por el currazo! Espero poder hacerlo funcionar!!

**Comment by bite-your-idols** [comment]
suerte!
