### ISSUE TITLE
Pc games

### ISSUE THREAD

**Issue by fdrslegs** [bite-your-idols/Gamestarter-Pi#33]
Hey there, 

I am completely new to this and have googled and googled and looked through previous issues. I would like to know how you added games like doom to be able to run on the Pi. I have a bunched of old DOS games and would like to add those. Any help explained like I'm a child will help.

Thanks!

**Comment by bite-your-idols** [comment]
there are two different thing. 
First are the libretro PC ports, including doom, quake or cave story. These are playable and included in gamestarter.
The second thing is to emulate dos games, for that you need dosbox emulator. Libretro port of this emulator is included in gamestarter, you can read some info about its configuration here:
https://github.com/libretro/Lakka/wiki/DOSBox

**Comment by fdrslegs** [comment]
So what makes Doom and Cave Story that was included Libreto PC Ports?

**Comment by bite-your-idols** [comment]
libretro ports are based on libretro cores developed for emulate that exact game.
- Cave Story ->nxengine_libretro
- DOOM ->prboom_libretro
- Quake -> tyrquake_libretro

I recommend to read some info about libretro & retroarch:
https://www.libretro.com/index.php/api/

**Comment by fdrslegs** [comment]
Alright cool thanks for the info! 

One final thing in regards to DOSBox, how I understand from the link you gave me, is that in order for the games to run they need to be in a config file? Or is it that I need to adjust the config file for gamestarter and then dump whatever dos.exe games I want into emulators/roms/dos ?

**Comment by bite-your-idols** [comment]
I really don't know... sorry... It is a system I personally don't use... but as far as I know, dosbox emulation in retroarch is not so good...
