### ISSUE TITLE
Emulators/Cores included

### ISSUE THREAD

**Issue by bite-your-idols** [bite-your-idols/Gamestarter-Pi#35]
## Most Popular Systems:
- [x] ARCADE ([lr Mame2003](https://github.com/libretro/mame2003-libretro) and [lr FBAlpha](https://github.com/libretro/fbalpha))
- [x] MSX/MSXII ([lr bluemsx](https://github.com/libretro/blueMSX-libretro) and [lr fmsx](https://github.com/libretro/fmsx-libretro))
- [x] Nintendo Game Boy/Game Boy Color ([lr Gambatte](https://github.com/libretro/Gambatte-libretro))
- [x] Nintendo NES ([lr fceumm](https://github.com/libretro/libretro-fceumm), [lr nestopia](https://github.com/libretro/nestopia) and [lr quicknes](https://github.com/libretro/QuickNES_Core))
- [x] Super Nintendo ([lr snes9x2002](https://github.com/libretro/snes9x2002), [lr snes9x2005](https://github.com/libretro/snes9x2005) and [lr snes9x2010](https://github.com/libretro/snes9x2010))
- [x] Nintendo Game Boy Advanced ([lr gpsp](https://github.com/libretro/gpsp) and [lr mgba](https://github.com/libretro/mgba))
- [x] Nintendo 64 ([lr glupen64](https://github.com/GLupeN64/GLupeN64) and [lr mupen64plus](https://github.com/libretro/mupen64plus-libretro))
- [x] Neo-Geo ([lr FBAlpha](https://github.com/libretro/fbalpha))
- [x] Sega Master System ([lr picodrive](https://github.com/libretro/picodrive) and [lr genesis_plus_gx](https://github.com/libretro/Genesis-Plus-GX))
- [x] Sega Megadrive/MegaCD ([lr picodrive](https://github.com/libretro/picodrive) and [lr genesis_plus_gx](https://github.com/libretro/Genesis-Plus-GX))
- [x] Sony Playstation ([lr pcsx_rearmed](https://github.com/libretro/pcsx_rearmed))
- [x] Sony PSP ([lr ppsspp](https://github.com/libretro/libretro-ppsspp))
- [x] Turbografx/PC Engine/PC Engine CD ([lr mednafen_pce_fast](https://github.com/libretro/beetle-pce-fast-libretro) and [lr mednafen_supergrafx](https://github.com/libretro/beetle-supergrafx-libretro))

## Additional Systems:
- [x] AMIGA ([lr uae4arm](https://github.com/r-type/uae4arm-libretro) or [UAE4ARM ](https://github.com/Chips-fr/uae4arm-rpi))
- [x] ARCADE ([lr Mame2000](https://github.com/libretro/mame2000-libretro))
- [x] Atari 2600 ([lr stella](https://github.com/libretro/stella-libretro))
- [x] Atari 7800 ([lr prosystem](https://github.com/libretro/prosystem-libretro))
- [x] Atari Lynx ([lr handy](https://github.com/libretro/libretro-handy))
- [x] Game & Watch ([lr gw](https://github.com/libretro/gw-libretro))
- [x] Magnavox Odyssey/Phillips Videopac ([lr o2em](https://github.com/libretro/libretro-o2em))
- [x] NeoGeo Pocket/NeoGeo Pocket Color ([lr mednafen_ngp](https://github.com/libretro/beetle-ngp-libretro))
- [x] Port: Cave Story ([lr nxengine](https://github.com/libretro/nxengine-libretro))
- [x] Port: Dinothawr ([lr dinothawr](https://github.com/libretro/Dinothawr))
- [x] Port: Doom ([lr prboom](https://github.com/libretro/libretro-prboom))
- [x] Port: Quake ([lr tyrquake](https://github.com/libretro/tyrquake))
- [x] Sega GameGear ([lr genesis_plus_gx](https://github.com/libretro/Genesis-Plus-GX))
- [x] Vectrex ([lr vecx](https://github.com/libretro/libretro-vecx))
- [x] Wondeswan/Wonderswan Color ([lr mednafen_wswan](https://github.com/libretro/beetle-wswan-libretro))
- [x] ZX Spectrum ([lr fuse](https://github.com/libretro/fuse-libretro))

## Requested Systems:
- [x] Atari 800 ([lr atari800](https://github.com/r-type/libretro-atari800))
- [ ]  Atari ST ([lr hatari](https://github.com/libretro/hatari))
- [x] DosBox ([lr dosbox](https://github.com/libretro/dosbox-libretro))
- [x] ScummVM ([lr scummvm](https://github.com/libretro/scummvm))
- [ ] ScummVM ([scummvm](https://github.com/scummvm/scummvm))

## Experimental Cores (WIP) - Installation from addon settings:
- [x] AMIGA ([lr fsuae](https://github.com/libretro/libretro-fsuae))
- [x] ARCADE ([lr mame2010](https://github.com/libretro/mame2010-libretro))
- [x] Nintendo DS ([lr desemume](https://github.com/libretro/desmume))
- [x] Nintendo DS ([DraStic](https://www.raspberrypi.org/forums/viewtopic.php?f=78&t=170820))
- [x] Sega Saturn ([lr yabause](https://github.com/libretro/yabause))

**Comment by antaril** [comment]
is it pissible to add atari st emulator? That would be great!!!

**Comment by antaril** [comment]
btw great job ;)

**Comment by bite-your-idols** [comment]
I see there is an experimental libretro core for atari st based on hatari emulator, but it seems is a little "work in-progress" by now: https://retropie.org.uk/forum/topic/4866/libretro-hatari-how-to-install/10
If you want, you can install retropie, compile it from experimetal cores menu and grab binary, then tr to use it in LibreELEC/OpenELEC with gamestarter.
If you do so, please, let us know your advances.

**Comment by bravesfan171** [comment]
Where can I add roms for the Gameboy Advance? Do I need to create a "gba" folder under Roms?

**Comment by bite-your-idols** [comment]
Yes, it should be already there but I see it is an error in last version, I will fix it, thanks for the advice!

**Comment by bite-your-idols** [comment]
I am testing the new DraStic emulator por Nintendo DS, it seems very promising:
https://www.raspberrypi.org/forums/viewtopic.php?t=170820&p=1104991

**Comment by bite-your-idols** [comment]
@antaril I compiled hatari_libretro core from RetroPie and zipped with its needed libs, you can download from here:https://github.com/bite-your-idols/Gamestarter-Pi/raw/master/packages/libretro-cores-ex/hatari_libretro.7z
then you can place libs in its folder and core with the rest of them and start making tests. If you can get any achievement please let us know.

**Comment by bite-your-idols** [comment]
Workaround for using SCUMMVM standalone emulator with Gamestarter:
https://forum.libreelec.tv/thread-287-post-21634.html#pid21634

**Comment by antaril** [comment]
thx very much, i will try!!!

**Comment by antaril** [comment]
Hi,
i have copied the three files to:
.kodi/addons/script.gamestarter/resources/bin/libretro-cores

but it says failed load core!

In Core list there is now Atari ST.. core... but games wont start!

**Comment by bite-your-idols** [comment]
just hatari_libretro.so file goes in that folder, the other 2 are lib dependencies, you must put them in .kodi/addons/script.gamestarter/lib/ (if folder doesn't exist, create it).

If still does not work, try this ssh command:
`ldd .kodi/addons/script.gamestarter/resources/bin/libretro-cores/hatari_libretro.so`
to check if there is any else lib missing.

**Comment by antaril** [comment]
ok, now there are all in the right folders. But Games wont start. Libreelec just reboots and Gamestarter crashes i think!


Here is the Shell command...


ldd .kodi/addons/script.gamestarter/resources/bin/libretro-cores/hatari_libretro.so
        linux-vdso.so.1 (0x7ed8a000)
        /usr/lib/libarmmem.so (0x756ee000)
        libz.so.1 => /usr/lib/libz.so.1 (0x756db000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x756b3000)
        libm.so.6 => /usr/lib/libm.so.6 (0x75635000)
        libcapsimage.so.5 => /storage/.kodi/addons/script.gamestarter/lib/libcapsimage.so.5 (0x7560f000)
        libc.so.6 => /usr/lib/libc.so.6 (0x754d6000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x754aa000)
        /usr/lib/ld-linux-armhf.so.3 (0x54b41000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x75365000)

**Comment by bite-your-idols** [comment]
ok, it seems no other lib is missing, right. we need to know what is the output of gamestarter.log. Activate debug options in retroarch, try to load that core and look into log.

**Comment by antaril** [comment]
where is the folder for the log? Sorry cant find

**Comment by antaril** [comment]
ok, i found it:


.kodi/userdata/addon_data/script.gamestarter

log file 👍 

http://txt.do/d1ooy

**Comment by bite-your-idols** [comment]
I can see in your log you are missing a TOS.img required file, 
`Can not load TOS file:
'/storage/.kodi/addons/script.gamestarter/resources/bin/tos.img'`

you can read more about it here (starting al line 287):
https://github.com/libretro/hatari/blob/master/doc/manual.html

**Comment by antaril** [comment]
ok, its done... but dont work ;(

there is no nvram...

log:


[libretro-test]: Got size: 640 x 480.
Hatari v1.8.0, compiled on:  Feb  1 2017, 22:48:57
IPF : IPF_Init
IPF : capsimage library version release=5 revision=1
Configured max Hatari resolution = 640x480, optimal for ST = 832x588
Inserted disk '/storage/emulators/roms/atarist/Terminator II - Judgemant Day (1992)(Ocean)(Disk 1 of 2)[cr Elite][t].st' to drive A:.
NVRAM not found at '/storage/.hatari/hatari.nvram'
Bus error (core dumped)
::Gamestarter:: -> disable alsa...
::Gamestarter:: -> restart kodi...

**Comment by bite-your-idols** [comment]
maybe it is looking for needed files in /storage/.hatari and we need to make a symlink to gamestarter folder... or maybe we reach a dead-end... 
you can ask for help in its repo: https://github.com/libretro/hatari/issues
good luck!

**Comment by tjpreissig** [comment]
First thanks for the awesome work you've done, and second sorry if this is has been answered somewhere but I am stuck.
I've loaded a ton of ROMS in the correct folders and the NES, Mega Drive, and NES all work great.  of the few hundred SNES games I added only a small handful are recognized.  The folder contains SMC, SRM, & ZST extensions.  Will only one of these work?

**Comment by bite-your-idols** [comment]
Snes cores detect the following extensions:
.bin .smc .sfc .fig .swc .mgd .zip .BIN .SMC .SFC .FIG .SWC .MGD .ZIP

Are you using Kodi's Advanced Emulator Launcher, emulationstation or Retroarch?

**Comment by tjpreissig** [comment]
Retroarch, scan directory and then only a few show up, should I be using one of the other 2 ways?

**Comment by bite-your-idols** [comment]
Retroarch just find games named according to its database, so you must rename all collections (there are some sofotware for this, just google it) in order to match. Ifyou use Emulationsation or AdvancedLauncher all roms with supported extensions are listed, no matter their name.

**Comment by tjpreissig** [comment]
Using Emulationstation worked perfectly! thank you.  but is there a way to make it exit emulators back to Emulationstation instead of retroarch?

**Comment by bite-your-idols** [comment]
If you exit a game you should go back to ES. You can enter retroarch menu then exit retroarch or you can use a button combo to exit. You can see default one in retroarch settings (I think L1+L2+R1+R2) or you can assing custom one in hotkeys settings.

**Comment by mkli90** [comment]
What about PlayStation2? Also: I tried using PAL roms for PSX, but they don't work. NTSC work just fine. I added a PSX PAL Bios to the /emulator/bios directory but still nothing. Has someone a solution for that?

**Comment by bite-your-idols** [comment]
There is no PS2 emulator for RPi. I can play both NTSC and PAL PSX games in my pi... it seems it is an issue with your system bios files...

**Comment by mkli90** [comment]
Thanks for the quick answer @bite-your-idols. Could you show me what system bios files you have so I could check them maybe? Also the loading times for the PSX games is rather long compared to (S)NES/N64 etc. I reckon this is normal, right?

**Comment by bite-your-idols** [comment]
yes, long loading times are normal... here you have needed bios files:
http://www.lakka.tv/doc/BIOSes/

**Comment by mkli90** [comment]
Yes, thank you. I found this page already but I removed my three bios files and re-added them. Now it's working perfectly. Thank you! About that ps2 emulator again. What about http://pcsx2.net/. This might be a starting point, right? Has somebody already tried to get a RPi port out of this? If not I'd be willing to do so probably.

**Comment by bite-your-idols** [comment]
https://retropie.org.uk/forum/topic/288/ps2-emu-on-pi3-possible

**Comment by mkli90** [comment]
Oh right, fair enough, Thanks. Metal Gear Solid on PSX it is then! Anyway, keep up the awesome work!

**Comment by kimme** [comment]
Is it possible to get C64 games to work with this addon?

**Comment by bite-your-idols** [comment]
Since there is no libretro core for c64 only way to make it work in Gamestarter is trying to setup and launch VICE emulator, but it is not something I am going to work in. If someone wants to compile vice binary or grab it from another distro (and its required libs) and edits gamestarter launcher scripts I can help him to achieve that.

**Comment by bite-your-idols** [comment]
VICE libretro port included in latest v2.8 Gamestarter update.
Also, some new cores included from lakka 2.0
