### ISSUE TITLE
Retroarch 2.6 hangs on quit

### ISSUE THREAD

**Issue by SzymonZy** [bite-your-idols/Gamestarter-Pi#38]
When i want to quit a game i press l1+r1+start+select and chose quit from quick menu. Always at this point Retroatch hangs (background animation works) and nothing happens until I press ctrl+alt+del.

**Comment by bite-your-idols** [comment]
Which Raspberry Pi model are you using? in which libreelec/openelec version?
please copy/paste gamestarter.log

**Comment by SzymonZy** [comment]
Error exists if you exit ScummVM and N64 emulator (not always). On SNES everything is ok. 

There is no log on device.

**Comment by bite-your-idols** [comment]
ScummVM is a little buggy core, so you can expect issues like that. 
Glupen64 core should work ok, it is weird.
But the weirdest thing is the fact that you have no log file... 
Can you look again when playing a working core?
