### ISSUE TITLE
No sound on RPi3 with LibreELEC

### ISSUE THREAD

**Issue by fpytloun** [bite-your-idols/Gamestarter-Pi#39]
Hello,

thank you for great Kodi addon.
Unfortunately I can't get audio working on Raspberry Pi 3 running LibreELEC 7.0.2. I tried alsa, sdl and pulse (as libreelec is using pulseaudio, I supposed this one will work correctly) but no result (no analog or HDMI output) :-/

Found nothing in logs except for this:
```
::Gamestarter:: -> disable alsa...
::Gamestarter:: -> restart kodi...
```

But commenting out that modprobe/rmmod didn't any better.

**Comment by bite-your-idols** [comment]
Ok, let's try something.
Connect by ssh and try editing boot config:
`mount -o remount,rw /flash
nano /flash/config.txt `

Then, make sure gamestarter installation has add this parameter (if not include and test again):
`dtparam=audio=on`

There change/add these parameters:
`hdmi_force_edid_audio=1
hdmi_group=1
hdmi_mode=16`

Reboot and try again.

If you still have no sound, when in retroarch/emulation try this command:
`aplay -l `

if your card is not numbered 0, you can try editing retroach audio settings, and change hardware value to
`hw:1,1`
 
where "1" and "1" are the numbers given in previous command.

**Comment by fpytloun** [comment]
Unfortunately no change.
`aplay -l` gives me same devices as before config change (when snd_bcm2835 is loaded):

```
rpi01:~ # aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

Even playing wav file using aplay doesn't produce any sound.

**Comment by fpytloun** [comment]
Ok, got it.. :-)
Needed to manually set routing to analog output when gamestarter is launched:
```
amixer -c 0 cset numid=3 1
```

It would be good to have this as an configurable option to select audio output:
0 = auto
1 = analog
2 = HDMI

**Comment by bite-your-idols** [comment]
I'm glad it is working for you. I will consider your issue for next updates, this can help someone else with the same problem.

**Comment by fpytloun** [comment]
One more note - it should be also good to be able to disable loading snd module at all in case someone is using hifiberry.

**Comment by jefferyto** [comment]
I have this same issue, and the same command (`amixer -c 0 cset numid=3 2`, for HDMI) fixes it, though the setting is lost every time I quit and restart RetroArch, I believe because the `snd_bcm2835` module is removed after quitting RetroArch.

As a workaround, I have added the command after `modprobe snd_bcm2835` in `script.gamestarter/resources/bin/gamestarter.start`, though I will need to redo this "fix" after every addon update. I agree with @fpytloun that it would be good to have a configurable option for this.

Also, I don't see why this issue should be closed, since the problem still exists and no solution has been added to the code. Manually running the command or editing the start script is only a workaround.

**Comment by bite-your-idols** [comment]
alsa module start/disable removed in latest v2.8 update

**Comment by sadsfae** [comment]
Just wanted to comment and say this fixed my no sound issue with gamestarter on rpi3 and libreelec 8.0.2.

> Ok, let's try something.
> Connect by ssh and try editing boot config:
> ```mount -o remount,rw /flash```
> ```nano /flash/config.txt```
> 
> Then, make sure gamestarter installation has add this parameter (if not, include it and test again):
>```dtparam=audio=on```
> 
> There, change/add these parameters:
> ```hdmi_force_edid_audio=1```
> ```hdmi_group=1```
>``` hdmi_mode=16```

After this and a reboot I now have sound, thank you.

**Comment by goddib** [comment]
Hi everyone,

for some reason I'm struggling to get sound. I'm using an external USB soundcard for playback which works fine in Kodi. Using aplay -l it's also the only device listed. Yet I have yet to get a single sound out of retroarch or an emulator.

Does anyone have any idea? I'm running the latest libreelec and gamestarter.

Cheers!

**Comment by wonder75** [comment]
Thanks a lot.
That fixed it for me too.
