### ISSUE TITLE
running latest OpenElec, got the OE build of gamestarter, won't boot.

### ISSUE THREAD

**Issue by Weisselberger** [bite-your-idols/Gamestarter-Pi#41]
Hello Bite Your Idols,

At first thanks for all your good work, I would like to know if I'm missing something, I've installed gamestarter on my Kodi. when I try to boot gamestarter the screen goes black and it simply reboots Kodi.

As far as I know I've used the correct settings in IARL and same thing happens when launching a title, black screen and Kodi reboot.

Am I missing something? TIA

**Comment by Weisselberger** [comment]
Running on a RPi 3

**Comment by bite-your-idols** [comment]
let's try some things...
- launch gamestarter addon (with retroarch as a default frontend).
- after gamestarter splash screen kodi reboots, right? paste here what is inside log:
/storage/.kodi/userdata/addon_data/script.gamestarter/gamestarter.log

Other user reported that latest retroarch compiled for LibreELEC/OpenELEC is missing some libs, if this is also your issue we will see in the log and we will continue trying to fix it.


My recommendation is to update to LibreELEC since OpenELEC is quite dead project...

**Comment by Weisselberger** [comment]
Here's my log, appears there's something missing ;)

OpenELEC:~/.kodi/userdata/addon_data/script.gamestarter # cat gamestarter.log
/storage/.kodi/addons/script.gamestarter/resources/bin/retroarch: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory
::Gamestarter:: -> disable alsa...
::Gamestarter:: -> restart kodi...
OpenELEC:~/.kodi/userdata/addon_data/script.gamestarter #

I am really glad I've got everything working (including Samba), afraid it will take a lot of time to reinstall everything in LE. I have to look into that.

**Comment by bite-your-idols** [comment]
Try downloading this file: https://github.com/bite-your-idols/Gamestarter-Pi/raw/master/packages/retroarch_1.3.6_LE7.zip

extract it and copy/paste retroarch file in /storage/.kodi/addons/script.gamestarter/resources/bin

then try again...

----

About LE update, you can update from OE to LE just downloading update files from here (scroll down to Manual Update / Migration from OpenELEC (.tar)):
https://libreelec.tv/downloads/

before updating you can make an image of your sd card, just in case... if you don't like LE or something is not working as you want, you can burn into your sd your previous created backup ;)

**Comment by Weisselberger** [comment]
Thanks, maybe I'll should just look into LE, another log:

OpenELEC:~/.kodi/userdata/addon_data/script.gamestarter # cat gamestarter.log
/storage/.kodi/addons/script.gamestarter/resources/bin/gamestarter.start: line 87: /storage/.kodi/addons/script.gamestarter/resources/bin/retroarch: Permission denied
::Gamestarter:: -> disable alsa...
::Gamestarter:: -> restart kodi...
OpenELEC:~/.kodi/userdata/addon_data/script.gamestarter #

**Comment by bite-your-idols** [comment]
when replacing retroarch, you need to give new file permissions (chmod a+x)

**Comment by Weisselberger** [comment]
Did an update to LE, without any issues, deleted everything related to Gamestarter and IARL, after fresh install:

gamestarter.log
/storage/.kodi/addons/script.gamestarter/resources/bin/retroarch: error while loading shared libraries: libbrcmEGL.so: cannot open shared object file: No such file or directory
::Gamestarter:: -> disable alsa...
::Gamestarter:: -> restart kodi...

**Comment by bite-your-idols** [comment]
this is weird... do you install the correct addon version for your LE version?

**Comment by Weisselberger** [comment]
I went for 2.6LE.A8, should I go for a stable version?

**Comment by bite-your-idols** [comment]
if you are running LibreELEC 7.0.2 you need Gamestarter OLE (Open/LibreELEC)
if you are running LibreELEC 8 alpha you need Gamestarter LE

**Comment by Weisselberger** [comment]
It all makes sense now, RetroArch boots when running gamestarter, so that seems to be working.

Now IARL doesn't seem to be working, but I'll figure that one out. Thanks so much for being so helpful!
