### ISSUE TITLE
Latest LibreELEC Alpha (7.90.010) - EmulationStation not working

### ISSUE THREAD

**Issue by lesydimitri** [bite-your-idols/Gamestarter-Pi#42]
Hi

I updated LibreELEC to the latest build (7.90.010)  and EmulationStation is no longer working (RetroArch does).

Contents of the gamestarter log:

ConfigPath /storage/.config/emulationstation
/storage/.kodi/addons/script.gamestarter/resources/bin/emulationstation: symbol lookup error: /storage/.kodi/addons/script.gamestarter/lib/libfreeimage.so.3: undefined symbol: png_init_filter_functions_neon
::Gamestarter:: -> disable alsa...
::Gamestarter:: -> restart kodi...

**Comment by bite-your-idols** [comment]
thanks for the advise, I am working on it...

**Comment by bite-your-idols** [comment]
Fixed!
You can re-install ES from addon settings (first you can make you config backup) or you can just replace this lib: https://github.com/bite-your-idols/Gamestarter-Pi/raw/master/packages/emulationstation/lib/libfreeimage.so.3
