### ISSUE TITLE
Change GBA core

### ISSUE THREAD

**Issue by FfReAkDude** [bite-your-idols/Gamestarter-Pi#45]
Hello,

I want to change my gba core to vba_next in emulationstation and advanced launcher. How can I do this? Do I have to edit a cfg-file? Or is there a possibility to chose the emulator in emulationstation or advanced launcher? In retroarch I can change the core and then select a gba-game, but when I try to start a gba-game through es or al, these programs use another core than vba_next and this one doesn't work (I already have a gba bios in my system folder).

Thank you!

**Comment by bite-your-idols** [comment]
Changing default emualtor in AL is so easy, just select the desired system, press context menu and look for launcher paramters, there change default core for the new one.

For achieveing the same in ES you have to edit this file:
/storage/.kodi/userdata/addon_data/script.gamestarter/emulationstation/es_systems.cfg
there you can edit all default cores, add new systems, delete not used ones... as you want. I recommend to backup your files before, you can do it from addon settings.

**Comment by FfReAkDude** [comment]
Thanks for your answer! Really useful. I will try it soon!
