### ISSUE TITLE
xmb Menu Driver - Clipped by overscan

### ISSUE THREAD

**Issue by Stavr0** [bite-your-idols/Gamestarter-Pi#46]
Running on OpenELEC 7.0 Raspberry Pi 3B
Launching GameStarter

Problem:
Menus and displays are clipped by overscan cannot be turned on in LCD TV.

**Comment by bite-your-idols** [comment]
it seems you need to deal with overscan:
https://www.raspberrypi.org/documentation/configuration/config-txt.md

**Comment by Stavr0** [comment]
Solution:
Edit **/storage/.kodi/userdata/addon_data/script.gamestarter/retroarch**

Edit line for menu scaling
> xmb_scale_factor = "95"

Edit lines for emulator cores
1080 resolution:
> custom_viewport_y = "24"
> custom_viewport_height = "960"

720 resolution:
> custom_viewport_y = "16"
> custom_viewport_height = "688"
