### ISSUE TITLE
"Menu toggle" and "Resume"

### ISSUE THREAD

**Issue by drrak** [bite-your-idols/Gamestarter-Pi#47]
If you run the game by **Gamestarter** and use the "Menu toggle", everything works as it should.

If you run the game by **Adv. Launcher** and use the "Menu toggle", then instead of the "Resume" and additional options, I only have a "Run" and "Remove".

RPi2, LibreELEC 7.0.3, Gamestarter 2.6

**Comment by bite-your-idols** [comment]
it is so weird.... can you enable retroarch debugging mode and post the gamestarter.log output?

When you press "menu toggle" button and get into that Run and Remove options screen, can you press cancel button to go to retroarch main menu?

**Comment by drrak** [comment]
Yes, I can press cancel button and go to retroarch main menu.

> 
Starting PCSX-ReARMed 
Running PCSX Version 1.9 (Jan 19 2016).
psxMap: warning: wanted to map @80000000, got 0x72f05000
Init new dynarec
testing if we can run recompiled code..
test passed.
warning: RAM is not directly mapped, performance will suffer
Mapped (RAM/scrp/ROM/LUTs/TC):
78000000/1f800000/1fc00000/08000000/73818000
found BIOS file: scph1001.bin
RGB565 supported, using it
plugin: plugins/builtin_gpu
plugin: plugins/builtin_spu
plugin: plugins/builtin_pad
plugin: plugins/builtin_pad
Plugins loaded.
Loaded CD Image: /media/PATYK-32GB/rom/ps1/Diablo/Diablo (USA) (En,Fr,De,Sv).bin.
selected sound output driver: libretro
CD-ROM Label: SLUS00619                       
CD-ROM ID: SLUS00619
CD-ROM EXE Name: SLUS_006.19;1
ari64_reset
Starting PCSX-ReARMed 
Running PCSX Version 1.9 (Jan 19 2016).
psxMap: warning: wanted to map @80000000, got 0x72f87000
Init new dynarec
testing if we can run recompiled code..
test passed.
warning: RAM is not directly mapped, performance will suffer
Mapped (RAM/scrp/ROM/LUTs/TC):
78000000/1f800000/1fc00000/08000000/73818000
found BIOS file: scph1001.bin
RGB565 supported, using it
plugin: plugins/builtin_gpu
plugin: plugins/builtin_spu
plugin: plugins/builtin_pad
plugin: plugins/builtin_pad
Plugins loaded.
Loaded CD Image: /var/media/PATYK-32GB/rom/ps1/Diablo/Diablo (USA) (En,Fr,De,Sv).bin.
selected sound output driver: libretro
CD-ROM Label: SLUS00619                       
CD-ROM ID: SLUS00619
CD-ROM EXE Name: SLUS_006.19;1
ari64_reset
::Gamestarter:: -> disable alsa...
::Gamestarter:: -> restart kodi...

>

**Comment by bite-your-idols** [comment]
I really don't know what is happening because both methods execute the same command with same parameters... it so strange... can you post the other output to compare between two behaviours?

Anyways, if you can press cancel and go to retroarch menu, then enter quick menu, this is just a weird minor issue, because you can use all retroarch features, right?

**Comment by drrak** [comment]
Everything works, the only problem is that I can not return to the game.

Only Doom is on the SD card, and the rest of the games on USB stick.

**Comment by bite-your-idols** [comment]
I can not see any clue in the log... I also run my games from a USB device so it is not the problem...

So, when you toggle menu, then press cancel button, you are still in retroarch menu, right? on the left, in retroarch settings, the first option should be "quick menu", if you select it you should have current core options and resume, restart, close options... don't you?

**Comment by drrak** [comment]
I have never used the "Quick menu", only "History" to return to the game. Anyway Quick menu > Resume works on all games. Thanks for the help.

**Comment by bite-your-idols** [comment]
ok, so you were using history... in that way it could be related with roms not placed in browse directory... anyways, quick menu is the proper way to achieve that, also, when you toggle menu, you should enter quick menu automatically... in theory...
