### ISSUE TITLE
Emulationstation Quick System Select

### ISSUE THREAD

**Issue by Serg86** [bite-your-idols/Gamestarter-Pi#50]
Hi, when viewing the list of games and trying to switch systems, it only goes one way, right. Pressing left does work, so the key is not unbound, but it also goes right.

**Comment by bite-your-idols** [comment]
you are right... I need to test latest compilations...

**Comment by Serg86** [comment]
L+R for Page Down and Page Up also don't seem to work, tested both L/R Top and L/R Bottom

**Comment by bite-your-idols** [comment]
I updated ES and now left/right issue is fixed, you can update from addon settings or downloading package and manually reinstalling from here: https://github.com/bite-your-idols/Gamestarter-Pi/raw/master/packages/emulationstation.tar.gz

About page up/down, I don't know if it is an issue or it is just a not included feature for this ES version.
