### ISSUE TITLE
install-es.sh getting 404 from github

### ISSUE THREAD

**Issue by AussieBrad** [bite-your-idols/Gamestarter-Pi#52]
When selecting to install ES as frontend  the install-es.spy script tries to download another install-es.sh from https://github.com/bite-your-idols/Gamestarter-Pi/raw/master/scripts/install_es.sh.

Github is reporting 404 up to the raw directory

RPI 3, libreElec 7.95.2, gamestarter downloaded and installed yesterday

**Comment by bite-your-idols** [comment]
Did you download latest release 2.7? That file you are requesting is not used since several releases...
It should get install_extras.sh from github instead install_es.sh

**Comment by AussieBrad** [comment]
You were correct, I don't know how I downloaded an old version. Thanks for your help and effort putting gamestarter together
