### ISSUE TITLE
ES strange behavior, RA no database

### ISSUE THREAD

**Issue by thekk1** [bite-your-idols/Gamestarter-Pi#56]
Hi Guys,
i installed latest LibreELEC (7.95.3) testbuild and Gamestarter addon.
First, if i setup ES as frontend and start it, Kodi restarts after a short blackscreen.
In this case, Kodi is rising up the volume over HDMI continously and I cant stop it.
Neither after a reboot or deleting addon data in .kodi directory.
I just can reinstall LibreELEC then.

My other problem is, if i use retroarch as frontend, it creates no gamedatabase if i search for folders or files.
I have copied my roms in the desriped folders and if I search it seems that he find all 93 files but after that, no new entries in menu...

Additional to that, if i launch a game over "load content" the gamedata arent saved after i quit the game.

**Comment by bite-your-idols** [comment]
1- Strange thing... You should connect via ssh and run:
`ldd /storage/.kodi/addons/script.gamestarter/resources/bin/emulationstation`
then:
`systemctl stop kodi`
finaly:
`/storage/.kodi/addons/script.gamestarter/resources/bin/emulationstation`
output must tell us what is going on...

2- You need to update/download retroarch databases before you scan and scrape a directory. Also make sure you named your roms according to its database.

3- Auto save is not activated by default. When in a game, you should manually save/load your state. 

3-
