### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by ivangotoy** [bite-your-idols/Gamestarter-Pi#57]
Hello, is it possible to update this splendid addon for LE 9 eg. Kodi 18 - LibreELEC Testbuilds for RaspberryPi (Kodi 18.0).

cat gamestarter_retroarch.log 
/storage/.kodi/addons/script.gamestarter/resources/bin/retroarch: error while loading shared libraries: libavcodec.so.56: cannot open shared object file: No such file or directory

while LE uses libavcodec.so.57.48.101 (.so.57) as of today.

**Comment by bite-your-idols** [comment]
When firts Libreelec/kodi18 testbuilds appeared I test Gametarter on it and it worked...
Now, I've just tried it in this build: http://forum.kodi.tv/showthread.php?tid=298461&pid=2530788#pid2530788 and it still works...

Which testbuilds are you using? are you using LE8 addon version?

**Comment by ivangotoy** [comment]
Thanks for the heads up, reinstalled LE anew and script.gamestarter-v2.7-LE8.zip worked like a charm. All good now.

**Comment by bite-your-idols** [comment]
nice to read that!
