### ISSUE TITLE
No advanced launcher after install

### ISSUE THREAD

**Issue by bigM1k3** [bite-your-idols/Gamestarter-Pi#59]
I'm new to pi and Kodi, so bare with me. I installed an Omsd build that under system settings it shows a 17.1 build. I downloaded the install file for ganestarter using the 2.7 LE8 zip. After installing from zip, and running, it says reboot. But when I reboot advanced launcher isn't under my programs and when I try to download and  update the emulation station and other things in the settings of ganestarter, nothing happens. It seems like nothing is happening when I open ganestarter except it quickly telling me to reboot. I made sure it was enabled in add ons as well. Can you please help me figure out what I'm doing wrong?

**Comment by bite-your-idols** [comment]
Only works in LibreELEC and OpenELEC.
