### ISSUE TITLE
Retroarch online updater can replace OpenELEC with Lakka distro

### ISSUE THREAD

**Issue by dnicolier** [bite-your-idols/Gamestarter-Pi#6]
If the option Update Lakka is used in the online updater of Retroarch, the tar update downloaded will be used by OpenELEC on the next reboot to replace OpenELEC distro with Lakka. This option should probably be disabled to avoid data loss.

This is a great addon, keep up the good work :)

**Comment by bite-your-idols** [comment]
OMG! I didn't test that option, I just supposed it will give an error... I am going to fix it ASAP. 
Thanks for reporting!

**Comment by bite-your-idols** [comment]
Retroarch downgraded to previous non-lakka binary until I can get a newer non-lakka binary.
