### ISSUE TITLE
Gamestarter v2.8, Commodore 64 (vice)

### ISSUE THREAD

**Issue by drrak** [bite-your-idols/Gamestarter-Pi#60]
_Google translator:_
I have the latest version 2.8 (LibreELEC 7.0.3, RPi2). Everything works fine, except c64 emulator. After launching it immediately throws me into Kodi. Example from Adv. Launcher (launchers.xml):
> 		<launcher>
> 			<id>7f5913b7e72893c86780d2f473ededbc</id>
> 			<name>C64</name>
> 			<category>default</category>
> 			<application>/storage/.kodi/addons/script.gamestarter/resources/bin/gamestarter.sh</application>
> 			<args>vice "%rom%"</args>
> 			<rompath>/var/media/PATYK-32GB/rom/c64/</rompath>
> 			<thumbpath>/storage/.kodi/userdata/addon_data/plugin.program.advanced.launcher/thumbs/</thumbpath>
> 			<fanartpath>/storage/.kodi/userdata/addon_data/plugin.program.advanced.launcher/fanarts/</fanartpath>
> 			<trailerpath></trailerpath>
> 			<custompath></custompath>
> 			<romext>crt|d64|prg|t64|tap|zip</romext>
> 			<platform>Commodore 64</platform>
> 			<thumb>/storage/.kodi/userdata/addon_data/script.gamestarter/frontend-assets/amiga.jpg</thumb>
> 			<fanart>/storage/.kodi/userdata/addon_data/script.gamestarter/frontend-assets/amiga_fanart.jpg</fanart>
> 			<genre></genre>
> 			<release></release>
> 			<publisher></publisher>
> 			<launcherplot></launcherplot>
> 			<finished>false</finished>
> 			<minimize>false</minimize>
> 			<lnk></lnk>
> 			<roms>
> 				<rom>
> 					<id>d8b810a99cc1ad283e6eef5f3e3d616f</id>
> 					<name>River Raid</name>
> 					<filename>/var/media/PATYK-32GB/rom/c64/River_Raid.crt</filename>
> 					<thumb></thumb>
> 					<fanart></fanart>
> 					<trailer></trailer>
> 					<custom></custom>
> 					<genre></genre>
> 					<release></release>
> 					<publisher></publisher>
> 					<gameplot></gameplot>
> 					<finished>false</finished>
> 					<altapp></altapp>
> 					<altarg></altarg>
> 				</rom>
> 			</roms>
> 		</launcher>

**Comment by bite-your-idols** [comment]
correct core name is "vice_x64" as you can see here: https://github.com/bite-your-idols/Gamestarter-Pi/tree/master/packages/libretro-cores

also, if using AdvancedLauncher does not work something you can always try it using retroarch directly. You can "Load content and detec core" from there.

**Comment by drrak** [comment]
I corrected the name (vice_x64) and now it works. Thanks.
