### ISSUE TITLE
EmulationStation PSX issue

### ISSUE THREAD

**Issue by DasMeister22** [bite-your-idols/Gamestarter-Pi#62]
The PSX ROM list shows both .bin and .cue files, while it should only show the cue ones.

**Comment by bite-your-idols** [comment]
it displays all files with this extensions:
.bin .cue .cbn .img .iso .m3u .mdf .pbp .toc .z .znx .zip

You can remove .cue extensions if you want, you just need to edit [this file](https://github.com/bite-your-idols/Gamestarter-Pi/edit/master/packages/emulationstation/es_systems.cfg) located in
> /storage/.kodi/userdata/addons_data/script.gamestarter/emulationstation

I can not remove it for everybody, for example, I just use bin and zip files for psx games, I have no cue file in my psx folder so I couldn't list them...

**Comment by DasMeister22** [comment]
Thanks for the fast reply.
