### ISSUE TITLE
Repeated Crash on OE8.0.4

### ISSUE THREAD

**Issue by utdrmac** [bite-your-idols/Gamestarter-Pi#66]
Hi. I just installed the script.gamestarter-v2.8-OLE.zip on to my OpenELEC 8.0.4 RPi3 with Kodi 17. I enabled the Advanced Emulator Launcher as per the instructions and copied 1 test rom to /storage/emulators/roms/nes/ I did then a scan for new roms and it was detected.

However, each time I go to Add-Ons -> Gamestarter ->Exit Kodi and run RetroArch -> Yes, I see the Gamestarter logo on the screen for about 3 seconds, then Kodi starts up again.

I tried to launch the rom from Advanced Emulator Launcher, and that too simply causes Kodi to reboot.

    OpenELEC:~ # more /storage/.kodi/userdata/addon_data/script.gamestarter/gamestarter.log
    more: /storage/.kodi/userdata/addon_data/script.gamestarter/gamestarter.log: No such file or directory

**Comment by bite-your-idols** [comment]
Yes, in openelec 8 addon stopped working... Since LibreELEC is becoming "official" kodi OS I am not going to support OpenELEC any more so I recommend you to switch to LE8 what will cost you about 5 minutes.

**Comment by utdrmac** [comment]
Swapped to LibreELEC. GamestarterPi works and I've played a few ROMs but having video playback issues not experienced in OpenELEC. Thanks.
