### ISSUE TITLE
IARL Integration Issue

### ISSUE THREAD

**Issue by chewvodka** [bite-your-idols/Gamestarter-Pi#7]
I discovered an issue with the IARL Integration.  If you don't have IARL installed, and download it through the GameStarter config tabs, it downloads a version of IARL in a zip folder where the subfolder is called "plugin.program.iarl-master".  The -master bit causes IARL's setup wizard to fail because the python script is located in a different folder than where the addon is calling it from.  According to ZachMorris (the IARL author), downloading IARL from "HIS" GitHub doesn't have that problem.  So GameStarter is the blame, adding the extra -master bit on the end.

**Comment by bite-your-idols** [comment]
HI,
IARL addon's github page has no releases page so only way to download zip is from main github page. If I download it I get a file named "plugin.program.iarl-master.zip" and when unzipping the result is a folder named "plugin.program.iarl-master".
So I can not see any difference with the result of downloading/unzipping using Gamestarter...

**Comment by chewvodka** [comment]
I noticed that too.  If you look in his Wiki, he has instructions with 2 different links to his addon.  One is to get his repo [https://github.com/zach-morris/repository.zachmorris/releases/download/1.0.0/repository.zachmorris-1.0.0.zip](url) or to get his "latest" via the archive [https://github.com/zach-morris/plugin.program.iarl/archive/master.zip](url).  The only other option I see is via the "homepage" button to download the zip (which in turn creates that -master folder).

**Comment by bite-your-idols** [comment]
Hi!
you can replace the file /storage/.kodi/addons/script.gamestarter/resources/bin/install_iarl.sh with this updated one: https://github.com/bite-your-idols/Gamestarter-Pi/raw/master/resources/bin/install_iarl.sh
it will install the latest addon version with correct folder name. I will include it in my next release.
